### ISSUE TITLE
Im having an error

### ISSUE THREAD

**Issue by BLSTR13** [TDenisM/Netflix-4K-Script#3]
```
Traceback (most recent call last):
  File "D:\ytdl\Netflix-4K-Script\netflix.py", line 346, in <module>
    info = fetch_metadata_movie(BUILD, str(args.title[0]))
  File "D:\ytdl\Netflix-4K-Script\netflix.py", line 229, in fetch_metadata_movie
    cookies = parseCookieFile('cookies.txt')
  File "D:\ytdl\Netflix-4K-Script\netflix.py", line 187, in parseCookieFile
    cookies[lineFields[5]] = lineFields[6]
IndexError: list index out of range

**Comment by TDenisM** [comment]
!IMPORTANT! I'm not the author of this code - I just saved it for the futher digging in it
